"""Generate the SQL seed files from the Source Map CSV + the taxonomy below.
Run: python3 scripts/build_seeds.py   (re-run whenever the CSV or taxonomy changes)"""
import csv, json, os, re
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SEED = os.path.join(ROOT, 'supabase', 'seed')

def q(v):
    if v is None or v == '': return 'null'
    return "'" + str(v).replace("'", "''") + "'"

def slug(s): return re.sub(r'[^a-z0-9]+', '-', s.lower()).strip('-')

# ---------------------------------------------------------------- sources
rows = list(csv.DictReader(open(os.path.join(ROOT, 'data', 'source_map.csv'))))
NO_REDIS = ('Glama', 'Product Hunt', 'Crunchbase', 'Reddit', 'X (Twitter)', 'Artificial Analysis', 'Agentery', 'Wellknown', 'Agenstry', 'Agentic Index')
YES_REDIS = ('Official MCP Registry', 'GitHub REST', 'npm Registry', 'PyPI', 'LiteLLM', 'models.dev', 'Hacker News', 'A2A Agent Card')
def interval(r):
    t = (r['refresh'] or '').lower()
    for k, v in (('hour', '1 hour'), ('daily', '1 day'), ('day', '1 day'), ('week', '7 days'), ('month', '30 days')):
        if k in t: return v
    return None
out = ["-- Generated by scripts/build_seeds.py from data/source_map.csv — do not edit by hand",
       "-- 85 sources from the Source Map + 2 internal sources.",
       "insert into sources(code,name,url,layer,family,role,priority,access,structured,refresh,refresh_interval,legal,cost,redistribution_allowed,attribution_required,is_active,notes,evidence_url) values"]
vals = [
 "('SRC-000','Dreamotion editorial curation',null,'Internal','Manual','Source','P0','Manual','yes','on demand',null,'own data','free',true,false,true,'Taxonomy, manual verification, corrections',null)",
 "('SRC-900','Intendex probes (own observations)',null,'Internal','Probe','Source','P0','Own crawler','yes','daily','1 day','own data','free',true,false,true,'Agent-card probes, uptime checks, pricing snapshots made by our bots',null)"]
for r in rows:
    redis = 'false' if any(r['name'].startswith(n) for n in NO_REDIS) else ('true' if any(r['name'].startswith(n) for n in YES_REDIS) else 'null')
    attrib = 'true' if ('attribut' in (r['legal'] + r['notes']).lower()) else 'false'
    active = 'true' if (r['priority'] == 'P0' and r['role'] in ('Source', 'Both', 'Standard') and not r['name'].startswith('Glama')) else 'false'
    iv = interval(r)
    vals.append('(' + ','.join([q(r['id']), q(r['name']), q(r['url']), q(r['layer']), q(r['family']), q(r['role']),
        q(r['priority']), q(r['access']), q(r['structured']), q(r['refresh']), (q(iv) + '::interval') if iv else 'null',
        q(r['legal']), q(r['cost']), redis, attrib, active, q(r['notes'][:1000]), q(r['evidence_url'])]) + ')')
out.append(',\n'.join(vals))
out.append("on conflict (code) do update set name=excluded.name, url=excluded.url, priority=excluded.priority, legal=excluded.legal, notes=excluded.notes;")
open(os.path.join(SEED, '0100_sources.sql'), 'w').write('\n'.join(out) + '\n')

# ---------------------------------------------------------------- taxonomy
ENTITY_TYPES = [  # code, label, plural, url_prefix, is_listing, order
 ('agent','AI agent','AI agents','/agents',True,10), ('mcp_server','MCP server','MCP servers','/mcp',True,20),
 ('tool','Tool','Tools','/tools',True,30), ('model','Model','Models','/models',True,40),
 ('company','Company','Companies','/companies',True,50), ('integration','Integration','Integrations','/integrations',False,60),
 ('task','Task','Tasks','/tasks',False,70), ('capability','Capability','Capabilities','/capabilities',False,80),
 ('category','Category','Categories','/agents',False,90), ('protocol','Protocol','Protocols','/protocols',False,95),
 ('ad_agent','Advertising agent','Advertising agents','/ad-agents',True,100)]
RELATION_TYPES = [
 ('has_capability','has capability',None,'capability'), ('solves_task','solves task','agent','task'),
 ('requires_capability','requires capability','task','capability'), ('in_category','in category',None,'category'),
 ('integrates_with','integrates with',None,'integration'), ('made_by','made by',None,'company'),
 ('uses_model','uses model','agent','model'), ('exposes_mcp','exposes MCP server','agent','mcp_server'),
 ('alternative_to','alternative to','agent','agent')]
CATEGORIES = ['Coding','Research','Marketing','Sales','Customer Support','Finance','Data','Productivity','Browser & Computer Use','Business Operations']
PROTOCOLS = [('API','Public HTTP API'),('MCP','Model Context Protocol server'),('A2A','Agent2Agent protocol (agent card)'),
 ('Webhook','Outgoing webhooks'),('SDK','Official SDK'),('AdCP','Ad Context Protocol (agentic advertising)'),
 ('AAMP','IAB Tech Lab Agentic Advertising Management Protocols'),('UCP','Universal Commerce Protocol'),('AP2','Agent Payments Protocol')]
CAPS = ['Web Research','Web Scraping','Browser Automation','Computer Use','Data Extraction','Document Understanding','Data Analysis',
 'SQL Querying','Spreadsheet Automation','Forecasting','Report Generation','Summarization','Translation','Content Writing',
 'SEO Optimization','Image Generation','Video Generation','Voice Calls','Speech Transcription','Email Automation',
 'Social Media Management','Influencer Discovery','Lead Generation','Lead Enrichment','Lead Scoring','CRM Integration',
 'Outreach Sequencing','Meeting Scheduling','Calendar Management','Customer Chat','Ticket Triage','Knowledge Base QA',
 'Code Generation','Code Review','Test Generation','Debugging','DevOps Automation','Security Scanning','Workflow Orchestration',
 'API Integration','Payments','Invoicing','Bookkeeping','Price Monitoring','E-commerce Management','Procurement',
 'Travel Booking','Candidate Sourcing','Resume Screening','Competitor Monitoring']
assert len(CAPS) == 50
C = {c: slug(c) for c in CAPS}
T = lambda cat, name, *caps: (cat, name, caps)
TASKS = [
 # Coding (12)
 T('Coding','Write code from a specification','Code Generation','Test Generation'),
 T('Coding','Review pull requests','Code Review','Security Scanning'),
 T('Coding','Fix bugs in a codebase','Debugging','Code Generation'),
 T('Coding','Generate unit tests','Test Generation','Code Generation'),
 T('Coding','Migrate a codebase to a new framework','Code Generation','Test Generation','Code Review'),
 T('Coding','Build an internal tool','Code Generation','API Integration'),
 T('Coding','Automate CI/CD pipelines','DevOps Automation','Workflow Orchestration'),
 T('Coding','Scan code for vulnerabilities','Security Scanning','Code Review'),
 T('Coding','Write technical documentation','Content Writing','Summarization','Code Review'),
 T('Coding','Build a website','Code Generation','Image Generation'),
 T('Coding','Integrate two APIs','API Integration','Code Generation'),
 T('Coding','Monitor production incidents','DevOps Automation','Debugging','Summarization'),
 # Research (10)
 T('Research','Research competitors','Web Research','Competitor Monitoring','Report Generation'),
 T('Research','Research a company','Web Research','Lead Enrichment','Summarization'),
 T('Research','Do market research','Web Research','Data Analysis','Report Generation'),
 T('Research','Summarize academic papers','Document Understanding','Summarization'),
 T('Research','Monitor news on a topic','Web Research','Summarization'),
 T('Research','Build a literature review','Web Research','Document Understanding','Report Generation'),
 T('Research','Fact-check a document','Web Research','Document Understanding'),
 T('Research','Track regulatory changes','Web Research','Summarization','Competitor Monitoring'),
 T('Research','Analyze patents','Document Understanding','Data Analysis'),
 T('Research','Answer questions from internal documents','Knowledge Base QA','Document Understanding'),
 # Marketing (12)
 T('Marketing','Write SEO articles','Content Writing','SEO Optimization','Web Research'),
 T('Marketing','Find influencers','Influencer Discovery','Web Research'),
 T('Marketing','Manage social media accounts','Social Media Management','Content Writing','Image Generation'),
 T('Marketing','Create ad creatives','Image Generation','Content Writing','Video Generation'),
 T('Marketing','Produce short videos','Video Generation','Content Writing'),
 T('Marketing','Run email marketing campaigns','Email Automation','Content Writing'),
 T('Marketing','Audit website SEO','SEO Optimization','Web Scraping','Report Generation'),
 T('Marketing','Optimize for AI search (GEO)','SEO Optimization','Content Writing','Web Research'),
 T('Marketing','Translate marketing content','Translation','Content Writing'),
 T('Marketing','Monitor brand mentions','Web Research','Social Media Management','Summarization'),
 T('Marketing','Plan a content calendar','Content Writing','Calendar Management'),
 T('Marketing','Analyze campaign performance','Data Analysis','Report Generation'),
 # Sales (12)
 T('Sales','Find leads','Lead Generation','Web Research'),
 T('Sales','Qualify leads','Lead Scoring','Lead Enrichment','CRM Integration'),
 T('Sales','Enrich CRM contacts','Lead Enrichment','CRM Integration'),
 T('Sales','Send personalized outreach','Outreach Sequencing','Email Automation','Lead Enrichment'),
 T('Sales','Book sales meetings','Meeting Scheduling','Email Automation'),
 T('Sales','Make outbound sales calls','Voice Calls','Lead Scoring','CRM Integration'),
 T('Sales','Write sales proposals','Content Writing','Document Understanding'),
 T('Sales','Update the CRM after calls','Speech Transcription','CRM Integration','Summarization'),
 T('Sales','Forecast sales pipeline','Forecasting','CRM Integration','Data Analysis'),
 T('Sales','Research accounts before meetings','Web Research','Lead Enrichment','Summarization'),
 T('Sales','Follow up on quotes','Email Automation','CRM Integration'),
 T('Sales','Find B2B partners','Lead Generation','Web Research','Lead Scoring'),
 # Customer Support (10)
 T('Customer Support','Answer customer questions','Customer Chat','Knowledge Base QA'),
 T('Customer Support','Triage support tickets','Ticket Triage','Summarization'),
 T('Customer Support','Automate customer support','Customer Chat','Ticket Triage','Knowledge Base QA'),
 T('Customer Support','Answer support phone calls','Voice Calls','Knowledge Base QA'),
 T('Customer Support','Handle refund requests','Customer Chat','Payments','Workflow Orchestration'),
 T('Customer Support','Build a help center','Content Writing','Knowledge Base QA'),
 T('Customer Support','Support customers in many languages','Translation','Customer Chat'),
 T('Customer Support','Analyze customer feedback','Data Analysis','Summarization'),
 T('Customer Support','Track orders for customers','Customer Chat','E-commerce Management','API Integration'),
 T('Customer Support','Run satisfaction surveys','Email Automation','Data Analysis'),
 # Finance (10)
 T('Finance','Analyze financial documents','Document Understanding','Data Analysis'),
 T('Finance','Automate bookkeeping','Bookkeeping','Data Extraction'),
 T('Finance','Send and chase invoices','Invoicing','Email Automation'),
 T('Finance','Reconcile payments','Payments','Bookkeeping','Spreadsheet Automation'),
 T('Finance','Build financial models','Spreadsheet Automation','Forecasting'),
 T('Finance','Process expense receipts','Data Extraction','Bookkeeping'),
 T('Finance','Monitor company cash flow','Forecasting','Report Generation'),
 T('Finance','Research investment opportunities','Web Research','Data Analysis','Report Generation'),
 T('Finance','Prepare tax documents','Document Understanding','Bookkeeping'),
 T('Finance','Detect fraudulent transactions','Data Analysis','Payments'),
 # Data (10)
 T('Data','Extract website data','Web Scraping','Data Extraction'),
 T('Data','Query databases in plain language','SQL Querying','Data Analysis'),
 T('Data','Clean and merge spreadsheets','Spreadsheet Automation','Data Extraction'),
 T('Data','Build dashboards','Data Analysis','Report Generation'),
 T('Data','Extract data from PDFs','Document Understanding','Data Extraction'),
 T('Data','Monitor prices','Price Monitoring','Web Scraping'),
 T('Data','Generate reports','Report Generation','Data Analysis'),
 T('Data','Forecast demand','Forecasting','Data Analysis'),
 T('Data','Label and classify data','Data Extraction','Summarization'),
 T('Data','Build data pipelines','Workflow Orchestration','API Integration','SQL Querying'),
 # Productivity (8)
 T('Productivity','Manage my inbox','Email Automation','Summarization'),
 T('Productivity','Schedule meetings','Meeting Scheduling','Calendar Management'),
 T('Productivity','Take meeting notes','Speech Transcription','Summarization'),
 T('Productivity','Book travel','Travel Booking','Calendar Management'),
 T('Productivity','Summarize long documents','Summarization','Document Understanding'),
 T('Productivity','Draft emails','Email Automation','Content Writing'),
 T('Productivity','Create presentations','Content Writing','Image Generation','Report Generation'),
 T('Productivity','Transcribe audio and video','Speech Transcription','Translation'),
 # Browser & Computer Use (8)
 T('Browser & Computer Use','Fill web forms automatically','Browser Automation','Data Extraction'),
 T('Browser & Computer Use','Automate repetitive desktop tasks','Computer Use','Workflow Orchestration'),
 T('Browser & Computer Use','Test web applications','Browser Automation','Test Generation'),
 T('Browser & Computer Use','Book appointments online','Browser Automation','Calendar Management'),
 T('Browser & Computer Use','Compare products online','Browser Automation','Price Monitoring','Web Research'),
 T('Browser & Computer Use','Buy products online','Browser Automation','Payments','E-commerce Management'),
 T('Browser & Computer Use','Collect data behind logins','Browser Automation','Web Scraping'),
 T('Browser & Computer Use','Operate legacy software','Computer Use','Data Extraction'),
 # Business Operations (8)
 T('Business Operations','Recruit developers','Candidate Sourcing','Resume Screening','Outreach Sequencing'),
 T('Business Operations','Screen job applicants','Resume Screening','Meeting Scheduling'),
 T('Business Operations','Automate business workflows','Workflow Orchestration','API Integration'),
 T('Business Operations','Manage procurement','Procurement','Price Monitoring','Document Understanding'),
 T('Business Operations','Review contracts','Document Understanding','Summarization'),
 T('Business Operations','Manage an online store','E-commerce Management','Content Writing','Price Monitoring'),
 T('Business Operations','Analyze real estate','Data Analysis','Web Research','Report Generation'),
 T('Business Operations','Onboard new employees','Knowledge Base QA','Workflow Orchestration'),
]
assert len(TASKS) == 100, len(TASKS)
for _, n, caps in TASKS:
    for c in caps: assert c in C, (n, c)
used = {c for _, _, cs in TASKS for c in cs}
assert used == set(CAPS), set(CAPS) - used

o = ["-- Generated by scripts/build_seeds.py — Intendex taxonomy v0.1 (draft, editorial)",
     "-- 11 entity types · 9 relation types · 10 categories · 9 protocols · 50 capabilities · 100 tasks", ""]
o.append("insert into entity_types(code,label,plural,url_prefix,is_listing,sort_order) values\n" + ',\n'.join(
    f"({q(a)},{q(b)},{q(c)},{q(d)},{str(e).lower()},{f})" for a, b, c, d, e, f in ENTITY_TYPES) + "\non conflict (code) do nothing;")
o.append("insert into relation_types(code,label,from_type,to_type) values\n" + ',\n'.join(
    f"({q(a)},{q(b)},{q(c)},{q(d)})" for a, b, c, d in RELATION_TYPES) + "\non conflict (code) do nothing;")
ents = [('category', slug(c), c, None) for c in CATEGORIES] + \
       [('protocol', slug(p), p, d) for p, d in PROTOCOLS] + \
       [('capability', C[c], c, None) for c in CAPS] + \
       [('task', slug(n), n, None) for _, n, _ in TASKS]
o.append("insert into entities(type,slug,name,short_description,status,is_published,confidence) values\n" + ',\n'.join(
    f"({q(t)},{q(s)},{q(n)},{q(d)},'active',true,'high')" for t, s, n, d in ents) + "\non conflict (type,slug) do nothing;")
rel = []
for cat, n, caps in TASKS:
    rel.append((slug(n), 'in_category', 'category', slug(cat)))
    for c in caps: rel.append((slug(n), 'requires_capability', 'capability', C[c]))
o.append("""insert into relations(from_id,relation,to_id,evidence_level,confidence,source_id)
select f.id, x.rel, t.id, 'declared', 'high', source_id_of('SRC-000')
from (values\n""" + ',\n'.join(f"  ({q(a)},{q(b)},{q(c)},{q(d)})" for a, b, c, d in rel) + """
) as x(task_slug, rel, to_type, to_slug)
join entities f on f.type = 'task' and f.slug = x.task_slug
join entities t on t.type = x.to_type and t.slug = x.to_slug
on conflict do nothing;""")
open(os.path.join(SEED, '0101_intendex_taxonomy.sql'), 'w').write('\n\n'.join(o) + '\n')
print('sources', len(vals), '| taxonomy entities', len(ents), '| task relations', len(rel))
