"""Build supabase/seed/0300_payments.sql and supabase/INSTALL_PAYMENTS_1.sql from data/payments/*.json."""
import json, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
d = json.load(open(root / 'data/payments/protocols.json'))
prov = json.load(open(root / 'data/payments/providers.json'))
# strict rule: PayPal's suite is a product, not a protocol -> listed as provider only
protocols = [p for p in d['protocols'] if p['name'] != 'PayPal Agentic Commerce']
q = lambda o: json.dumps(o, ensure_ascii=False).replace('$pay$', '')
seed = f"""-- {len(protocols)} protocols and {len(prov)} payment providers, read on official pages (checked 2026-10-02).
-- Generated by scripts/build_payments_seed.py — do not edit by hand.
select ingest_payments($pay${q(protocols)}$pay$::jsonb, $pay${q(prov)}$pay$::jsonb);
"""
(root / 'supabase/seed/0300_payments.sql').write_text(seed)
mig = (root / 'supabase/migrations/0017_payments.sql').read_text()
check = """
-- check
select (select count(*) from v_protocols) as protocols,
       (select count(*) from v_payment_providers) as providers,
       (select count(*) from provider_fees where valid_to is null) as fee_lines,
       (select count(*) from relations where relation = 'supports_protocol') as provider_protocol_links,
       (select tools from protocol_mentions where protocol_slug = 'x402') as tools_mentioning_x402;
"""
(root / 'supabase/INSTALL_PAYMENTS_1.sql').write_text(
    "-- ELECTRA INDEX — INSTALL_PAYMENTS_1 : Payment Index (protocols, providers, public fees)\n"
    "-- Paste everything into Supabase > SQL Editor > Run.\n\n" + mig + "\n\n" + seed + check)
print(len(protocols), 'protocols', len(prov), 'providers')
