"""Build supabase/seed/0200_commercial_agents.sql and supabase/INSTALL_AGENTS_1.sql
from data/agents/*.json (researched vendor pages). Duplicates are merged on domain."""
import json, glob, re, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
def dom(u): return re.sub(r'^www\.', '', re.sub(r'^https?://', '', (u or '').lower().strip())).split('/')[0]
# domains hosting several distinct products: identify by product name, not by domain
SHARED = {'github.com', 'salesforce.com', 'hubspot.com', 'chatgpt.com', 'perplexity.ai', 'google.com', 'microsoft.com', 'amazon.com', 'aws.amazon.com', 'openai.com', 'anthropic.com', 'claude.ai'}
def slug(s): return re.sub(r'[^a-z0-9]+', '-', s.lower()).strip('-')
merged = {}
for f in sorted(glob.glob(str(root / 'data/agents/*.json'))):
    for a in json.load(open(f)):
        d = dom(a['website'])
        k = ('name:' + slug(a['name'])) if (d in SHARED or not d) else d
        if k not in merged:
            a = dict(a); a['themes'] = [a['theme']]; merged[k] = a; continue
        m = merged[k]
        if a['theme'] not in m['themes']: m['themes'].append(a['theme'])
        m['capabilities'] = list(dict.fromkeys(m['capabilities'] + a['capabilities']))
        # keep the plan list from the record whose pricing was verified
        if a.get('pricing_verified') and not m.get('pricing_verified'):
            for key in ('plans','pricing_url','pricing_verified','free_plan','free_trial'): m[key] = a[key]
        for key in ('api','mcp','open_source','github_repo'):
            if m.get(key) is None and a.get(key) is not None: m[key] = a[key]
agents = list(merged.values())
for a in agents:
    d = dom(a['website'])
    al = [{'type': 'other', 'value': 'agent:' + slug(a['name'])}] if (d in SHARED or not d) else [{'type': 'domain', 'value': a['website']}]
    if a.get('github_repo'): al.append({'type': 'github_repo', 'value': a['github_repo']})
    a['aliases'] = al
payload = json.dumps(agents, ensure_ascii=False).replace("$agents$", "")
seed = f"""-- {len(agents)} commercial AI agents, researched on vendor websites (SRC-049), duplicates merged on domain.
-- Generated by scripts/build_agents_seed.py — do not edit by hand.
select ingest_agents($agents${payload}$agents$::jsonb);
select classify_capabilities_keywords(5000, 'kw-v2');
select refresh_rankings();
"""
(root / 'supabase/seed/0200_commercial_agents.sql').write_text(seed)
mig = (root / 'supabase/migrations/0014_agents_pricing_value.sql').read_text()
check = """
-- check
select (select count(*) from entities where type = 'agent' and is_published) as agents,
       (select count(distinct entity_id) from price_points) as agents_with_prices,
       (select count(*) from price_points) as price_points,
       (select count(*) from mv_theme_rankings where provider_type = 'agent') as agent_theme_rows;
"""
(root / 'supabase/INSTALL_AGENTS_1.sql').write_text(
    "-- ELECTRA INDEX — INSTALL_AGENTS_1 : 200 commercial agents + prices + value in rankings\n"
    "-- Paste everything into Supabase > SQL Editor > Run.\n\n" + mig + "\n\n" + seed + check)
print(len(agents), 'agents')
